import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Script from "next/script";
import Providers from "./components/Providers";
import Header from "./components/Header";
import { ThemeProvider } from "./components/ThemeProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#000000] text-gray-900 dark:text-gray-100 transition-colors duration-300`}
			>
				<Script
					src="https://checkout.razorpay.com/v1/checkout.js"
					strategy="lazyOnload"
				/>
				<Providers>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
					>
						<Header />
						<main className="container mx-auto px-4 py-8">
							{children}
						</main>
					</ThemeProvider>
				</Providers>
				<Toaster
					richColors
					position="top-center"
					closeButton
					theme="dark"
				/>
			</body>
		</html>
	);
}
